import jiwer

## Steve Jobs
ultra_fast   = "Good morning and thank you for having me here today. My name is Steve Jobs, and I stand before you with a history of transforming ideas into groundbreaking realities. From founding Apple Ink, a pioneer in many realms, including personal computing and mobile phones, to investing in Pixar animation studios, which redefined animated storytelling. My focus has always been to innovate and push the boundaries of what's possible. Although I did not complete my formal education, opting out of Reed College, the experience reinforced my belief in following one's passions, a philosophy that has been the cornerstone of my career. Courses like calligraphy didn't just fill my time they shaped my vision for Apple's renowned aesthetic. I am known for being meticulous and demanding qualities that have driven the creation of products beloved around the world. My goal has always been to create not just gadgets but tools that enrich lives and in every team I've led, I've fostered an environment of creativity and excellence. I am eager to bring the same visionary mindset and drive for perfection to your esteemed company to create innovative solutions that meet the challenges of tomorrow. Thank you for considering me as a candidate."
fast         = "Good morning and thank you for having me here today. My name is Steve Jobs, and I stand before you with a history of transforming ideas into groundbreaking realities. From founding Apple INT, a pioneer in many realms, including personal computing and mobile phones, to investing in Pixar animation studios, which redefined animated storytelling. My focus has always been to innovate and push the boundaries of what's possible. Although I did not complete my formal education, opting out of Reed College, the experience reinforced my belief in following one's passions, a philosophy that has been the cornerstone of my career. Courses like calligraphy didn't just fill my time they shaped my vision for Apple's renowned aesthetic. I am known for being meticulous and demanding qualities that have driven the creation of products beloved around the world. My goal has always been to create not just gadgets but tools that enrich lives and in every team I've led, I've fostered an environment of creativity and excellence. I am eager to bring this same visionary mindset and drive for perfection to your esteemed company to create innovative solutions that meet the challenges of tomorrow. Thank you for considering me as a candidate."
standard     = "Good morning and thank you for having me here today. My name is Steve Jobs, and I stand before you with a history of transforming ideas into groundbreaking realities. From founding Apple INT, a pioneer in many realms, including personal computing and mobile phones, to investing in Pixar animation studios, which redefined animated storytelling. My focus has always been to innovate and push the boundaries of what's possible. Although I did not complete my formal education, opting out of Reed College, the experience reinforced my belief in following one's passions a philosophy that has been the cornerstone of my career. Courses like calligraphy didn't just fill my time they shaped my vision for Apple's renowned aesthetic. I am known for being the meticulous and demanding qualities that have driven the creation of products beloved around the world. My goal has always been to create not just gadgets but tools that enrich lives and in every team I've led, I've fostered an environment of creativity and excellence. I am eager to bring this same visionary mindset and drive for perfection to your esteemed company to create innovative solutions that meet the challenges of tomorrow. Thank you for considering me as a candidate."
reference    = "Good morning, and thank you for having me here today. My name is Steve Jobs, and I stand before you with a history of transforming ideas into groundbreaking realities. From founding Apple Inc.—a pioneer in many realms, including personal computing and mobile phones—to investing in Pixar Animation Studios, which redefined animated storytelling, my focus has always been to innovate and push the boundaries of what's possible. Although I did not complete my formal education, opting out of Reed College, the experience reinforced my belief in following one's passions—a philosophy that has been the cornerstone of my career. Courses like calligraphy didn't just fill my time; they shaped my vision for Apple's renowned aesthetic. I am known for being meticulous and demanding, qualities that have driven the creation of products beloved around the world. My goal has always been to create not just gadgets, but tools that enrich lives, and in every team I've led, I've fostered an environment of creativity and excellence. I am eager to bring this same visionary mindset and drive for perfection to your esteemed company, to create innovative solutions that meet the challenges of tomorrow. Thank you for considering me as a candidate."

# ## Donald Trump
# ultra_fast   = "Good afternoon My name is Donald Trump, a seasoned businessman, television personality and former president of the United States. With my unique background in real estate, embodying a charismatic and assertive nature, I have consistently demonstrated the leadership needed to navigate complex environments. My experience running the nation's administration and crafting policies has equipped me with a profound understanding of both the macro and micro drivers that influence business operations and economic landscape. A graduate of the Wharton School at the University of Pennsylvania, with a degree in economics, I have honed both strategic economic insights and real world business acumen, whether in the boardroom, on television with the apprentice or in the Oval office. I've made decisions that resonate with an audience and produce tangible results. My outspoken and sometimes controversial approach has often led to significant media attention but it underscores my commitment to standing firm on my principles and objectives. I am excited about the opportunity to apply my vast knowledge and skills to drive success and new challenges and ventures. Thank you for your consideration."
# fast         = "Good afternoon My name is Donald Trump, a seasoned businessman, television personality and former president of the United States. With my unique background in real estate, embodying a charismatic and assertive nature, I have consistently demonstrated the leadership needed to navigate complex environments. My experience running the nation's administration and crafting policies has equipped me with a profound understanding of both the macro and micro drivers that influence business operations and economic landscape. A graduate of the Wharton School at the University of Pennsylvania, with a degree in economics, I have honed both strategic economic insights and real world business acumen, whether in the board room, on television with the apprentice or in the Oval office. I've made decisions that resonate with an audience and produce tangible results. My outspoken and sometimes controversial approach has often led to significant media attention but it underscores my commitment to standing firm on my principles and objectives. I am excited about the opportunity to apply my vast knowledge and skills to drive success in new challenges and ventures. Thank you for your consideration."
# standard     = "Good afternoon My name is Donald Trump, a seasoned businessman, television personality and former president of the United States. With my unique background in real estate, embodying a charismatic and assertive nature, I have consistently demonstrated the leadership needed to navigate complex environments. My experience running the nation's administration and crafting policies equipped me with a profound understanding of both the macro and micro drivers that influence business operations and economic landscape. A graduate of the Wharton School at the University of Pennsylvania, with a degree in economics, I have honed both strategic economic insights and real world business acumen, whether in the boardroom, on television with the apprentice or in the Oval office. I've made decisions that resonate with an audience and produce tangible results. My outspoken and sometimes controversial approach has often led to significant media attention but it underscores my commitment to standing firm on my principles and objective. I am excited about the opportunity to apply my vast knowledge and skills to drive success in new challenges and ventures. Thank you for your consideration."
# reference    = "Good afternoon. My name is Donald Trump, a seasoned businessman, television personality, and former President of the United States. With my unique background in real estate, embodying a charismatic and assertive nature, I have consistently demonstrated the leadership needed to navigate complex environments. My experience running the nation's administration and crafting policies has equipped me with a profound understanding of both the macro and micro drivers that influence business operations and economic landscapes. A graduate of the Wharton School at the University of Pennsylvania with a degree in economics, I have honed both strategic economic insights and real-world business acumen. Whether in the boardroom, on television with \"The Apprentice,\" or in the Oval Office, I've made decisions that resonate with an audience and produce tangible results. My outspoken and sometimes controversial approach has often led to significant media attention, but it underscores my commitment to standing firm on my principles and objectives. I am excited about the opportunity to apply my vast knowledge and skills to drive success in new challenges and ventures. Thank you for your consideration."

# ## Elon Musk
# ultra_fast   = "Good morning my name is Elon Musk and it's a privilege to be here today. I'm a passionate entrepreneur with a background in engineering and economics and I've devoted my career to pioneering advancements in technology and sustainability. As founder and CEO of several transformative companies like SpaceX and Tesla, I've demonstrated a consistent ability to lead and innovate in fast paced challenging environments. My ambition is always to push the boundaries of what's possible to take calculated risks and to see projects through from conception to completion. With over two decades of experience and leadership roles, I bring a unique blend of technical knowledge and business acumen. My work with Solar City, Neuralink and the Boring Company underscores my commitment to addressing some of humanity's biggest challenges through groundbreaking solution. I am excited about the prospect of contributing my skills and perspective to your team, where I intend to foster a culture of continuous innovation and growth. Thank me for considering my application and I look forward to the opportunity to discuss how my background, skills and ambitions align with the goals of your organization. Thank you for your time."
# fast         = "Good morning my name is Elon Musk and it's a privilege to be here today. I'm a passionate entrepreneur with a background in engineering and economics and I've devoted my career to pioneering advancements in technology and sustainability. As founder and CEO of several transformative companies like SpaceX and Tesla, I've demonstrated a consistent ability to lead and innovate in fast paced challenging environments. My ambition is always to push the boundaries of what's possible to take calculated risks and to see projects through from conception to completion. With over two decades of experience and leadership roles, I bring a unique blend of technical knowledge and business acumen. My work with Solarcity, Nuralink and the Boring Company underscores my commitment to addressing some of humanity's biggest challenges through groundbreaking solutions. I am excited about the prospect of contributing my skills and perspective to your team, where I intend to foster a culture of continuous innovation and growth. Thank me for considering my application and I look forward to the opportunity to discuss how my background, skills and ambitions align with the goals of your organization. Thank you for your time."
# standard     = "Good morning my name is Elon Musk and it's a privilege to be here today. I'm a passionate entrepreneur with a background in engineering and economics and I have devoted my career to pioneering advancements in technology and sustainability. As founder and CEO of several transformative companies like SpaceX and Tesla, I've demonstrated a consistent ability to lead and innovate in fast paced challenging environments. My ambition is always to push the boundaries of what's possible to take calculated risks and to see projects through from conception to completion. With over two decades of experience and leadership roles, I bring a unique blend of technical knowledge and business acumen. My work with Solarcity, Neurolink and the Boring Company underscores my commitment to addressing some of humanity's biggest challenges through groundbreaking solution. I am excited about the prospect of contributing my skills and perspective to your team, where I intend to foster a culture of continuous innovation and growth. Thank me for considering my application and I look forward to the opportunity to discuss how my background, skills and ambitions align with the goals of your organization. Thank you for your time."
# reference    = "Good morning, My name is Elon Musk, and it's a privilege to be here today. I'm a passionate entrepreneur with a background in engineering and economics, and I've devoted my career to pioneering advancements in technology and sustainability. As founder and CEO of several transformative companies like SpaceX and Tesla, I've demonstrated a consistent ability to lead and innovate in fast-paced, challenging environments. My ambition is always to push the boundaries of what's possible, to take calculated risks, and to see projects through from conception to completion. With over two decades of experience in leadership roles, I bring a unique blend of technical knowledge and business acumen. My work with SolarCity, Neuralink, and The Boring Company underscores my commitment to addressing some of humanity's biggest challenges through groundbreaking solutions. I am excited about the prospect of contributing my skills and perspective to your team, where I intend to foster a culture of continuous innovation and growth. Thank we for considering my application, and I look forward to the opportunity to discuss how my background, skills, and ambitions align with the goals of your organization. Thank you for your time."

hypothesis_list = [ultra_fast, fast, standard]

# Create transformation function for the input text
transformation = jiwer.Compose([
    jiwer.ToLowerCase(),
    jiwer.RemoveMultipleSpaces(),
    jiwer.ExpandCommonEnglishContractions(),
    jiwer.RemovePunctuation(),
    jiwer.Strip(),
])

for hypothesis in hypothesis_list:    
    # Calculate WER
    wer_score = jiwer.wer(transformation(reference), transformation(hypothesis))
    print(f"WER: {wer_score}")